// <auto-generated />
namespace ChickenScratch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CK2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CK2));
        
        string IMigrationMetadata.Id
        {
            get { return "201510260649139_CK2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
